#!/usr/bin/env python3
"""
Run the differentiation loop to evolve the champion config.

Prerequisites
-------------
- benchmark/splits.json must exist (generated by run_baselines.py)
- results/baselines/vanilla_direct.json must exist
- results/sensor/sensor_report.json is optional

Outputs
-------
results/differentiation/differentiation_log.jsonl
results/differentiation/champion_history.json
results/differentiation/final_champion.yaml
results/differentiation/champion.yaml

Usage examples
--------------
python scripts/run_differentiation.py --max-iterations 20
python scripts/run_differentiation.py --dry-run --max-iterations 3
"""
from __future__ import annotations

import argparse
import logging
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import DEFAULT_MODEL, AgentConfig
from src.differentiator import Differentiator
from src.evaluator import load_tasks_from_dir
from src.llm_client import LLMClient
from src.mutator import Mutator
from src.safeguard import Safeguard
from src.sensor import SensorReport
from src.utils import load_env_file, load_json, save_json, setup_logging

logger = logging.getLogger(__name__)


def main() -> None:
    load_env_file()

    parser = argparse.ArgumentParser(description="Run the differentiation loop")
    parser.add_argument("--api-key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--max-iterations", type=int, default=20)
    parser.add_argument(
        "--min-improvement",
        type=float,
        default=0.02,
        help="Minimum dev-score delta to accept a challenger",
    )
    parser.add_argument(
        "--vital-threshold",
        type=float,
        default=1.0,
        help="Minimum vital-sign pass rate required for promotion",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Mock evaluations (no API calls) for loop verification",
    )
    parser.add_argument("--splits-path", default="benchmark/splits.json")
    parser.add_argument("--baselines-dir", default="results/baselines")
    parser.add_argument("--sensor-dir", default="results/sensor")
    parser.add_argument("--output-dir", default="results/differentiation")
    parser.add_argument("--benchmark-dir", default="benchmark/tasks")
    parser.add_argument(
        "--initial-config",
        default=None,
        help="Path to YAML config to start from (default: vanilla config)",
    )
    args = parser.parse_args()

    setup_logging()

    if not args.api_key and not args.dry_run:
        sys.exit("ERROR: set OPENAI_API_KEY or pass --api-key (or use --dry-run)")

    splits_path = Path(args.splits_path)
    if not splits_path.exists():
        sys.exit(f"ERROR: {splits_path} not found; run run_baselines.py first")

    splits = load_json(splits_path)
    dev_ids: list[str] = splits["dev"]
    vital_ids: list[str] = splits["vital_signs"]
    calib_ids: list[str] = splits["calibration"]

    logger.info(
        "Splits loaded: dev=%d  vital_signs=%d  calibration=%d  test=%d",
        len(dev_ids),
        len(vital_ids),
        len(calib_ids),
        len(splits.get("test", [])),
    )

    vanilla_path = Path(args.baselines_dir) / "vanilla_direct.json"
    solved_calib_ids: list[str] = []
    if vanilla_path.exists():
        vd = load_json(vanilla_path)
        solved_calib_ids = [
            tid
            for tid in calib_ids
            if vd.get("results", {}).get(tid, {}).get("passed", False)
        ]
        logger.info("Solved calibration tasks (for add_exemplar): %d", len(solved_calib_ids))
    else:
        logger.warning("%s not found; add_exemplar will have no examples pool", vanilla_path)

    sensor_report: SensorReport | None = None
    sensor_path = Path(args.sensor_dir) / "sensor_report.json"
    if sensor_path.exists():
        sensor_report = SensorReport.load(sensor_path)
        logger.info("Sensor report loaded. Suggested mutations: %s", sensor_report.suggested_mutations)
    else:
        logger.warning(
            "%s not found; running differentiation without sensor guidance "
            "(equivalent to no_sensor ablation)",
            sensor_path,
        )

    all_tasks = load_tasks_from_dir(args.benchmark_dir)
    task_map = {task.task_id: task for task in all_tasks}
    solved_calib_tasks = [task_map[tid] for tid in solved_calib_ids if tid in task_map]

    if args.initial_config:
        initial = AgentConfig.from_yaml(Path(args.initial_config))
        logger.info("Starting from config: %s", args.initial_config)
    else:
        initial = AgentConfig()
        logger.info("Starting from default vanilla config")

    llm = LLMClient(
        api_key=args.api_key or "dry-run-key",
        default_model=args.model,
        log_dir=Path(args.output_dir),
    )
    rng = random.Random(args.seed)
    mutator = Mutator(rng=rng)
    safeguard = Safeguard(vital_tasks=vital_ids, threshold=args.vital_threshold)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    initial.save(output_dir / "initial_config.yaml")

    differentiator = Differentiator(
        llm_client=llm,
        mutator=mutator,
        safeguard=safeguard,
        tasks=task_map,
        dev_task_ids=dev_ids,
        vital_task_ids=vital_ids,
        log_dir=output_dir,
        sensor_report=sensor_report,
        solved_calibration_tasks=solved_calib_tasks,
        max_iterations=args.max_iterations,
        min_improvement=args.min_improvement,
        rng=rng,
        dry_run=args.dry_run,
    )

    logger.info(
        "Starting differentiation: max_iterations=%d  vital_threshold=%.2f  dry_run=%s",
        args.max_iterations,
        args.vital_threshold,
        args.dry_run,
    )
    result = differentiator.run(initial)

    accepted = sum(1 for record in result.history if record.accepted)
    safeguard_rejections = sum(1 for record in result.history if record.reason == "safeguard")
    no_improvement = sum(1 for record in result.history if record.reason == "no_improvement")

    summary = {
        "final_score": result.final_score,
        "total_iterations": result.total_iterations,
        "converged": result.converged,
        "accepted_mutations": accepted,
        "safeguard_rejections": safeguard_rejections,
        "no_improvement_rejections": no_improvement,
        "total_cost_usd": result.total_cost_usd,
        "model": args.model,
        "max_iterations": args.max_iterations,
        "vital_threshold": args.vital_threshold,
        "dry_run": args.dry_run,
    }
    save_json(output_dir / "differentiation_summary.json", summary)

    logger.info("\n=== Differentiation Summary ===")
    logger.info("  Final dev score   : %.3f", result.final_score)
    logger.info("  Total iterations  : %d", result.total_iterations)
    logger.info("  Converged         : %s", result.converged)
    logger.info("  Accepted          : %d", accepted)
    logger.info("  Safeguard rejects : %d", safeguard_rejections)
    logger.info("  No-improvement    : %d", no_improvement)
    logger.info("  Total API cost    : $%.4f", result.total_cost_usd)
    logger.info("  Final config      : %s", output_dir / "final_champion.yaml")


if __name__ == "__main__":
    main()
