#!/usr/bin/env python3
"""
Run the differentiation loop on BugsInPy tasks.

Prerequisites
-------------
- benchmark/splits.json must exist (generated by run_baselines.py)
- results/baselines/vanilla_direct.json must exist
- results/sensor/sensor_report.json is optional

Outputs
-------
results/differentiation/differentiation_log.jsonl
results/differentiation/champion_history.json
results/differentiation/final_champion.yaml
results/differentiation/champion.yaml

Usage examples
--------------
python scripts/run_differentiation.py --max-iterations 15
python scripts/run_differentiation.py --dry-run --max-iterations 3
"""
from __future__ import annotations

import argparse
import logging
import os
import random
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.bugsinpy_loader import (
    DEFAULT_BUGSINPY_ROOT,
    DEFAULT_CACHE_ROOT,
    DEFAULT_WORKSPACE_ROOT,
    load_bugsinpy_task,
)
from src.config import DEFAULT_MODEL, AgentConfig
from src.differentiator import Differentiator
from src.llm_client import LLMClient
from src.mutator import Mutator
from src.safeguard import Safeguard
from src.sensor import SensorReport
from src.utils import load_env_file, load_json, save_json, setup_logging

logger = logging.getLogger(__name__)


def main() -> None:
    load_env_file()

    parser = argparse.ArgumentParser(description="Run differentiation on BugsInPy tasks")
    parser.add_argument("--api-key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--max-iterations", type=int, default=15)
    parser.add_argument(
        "--min-improvement", type=float, default=0.02,
        help="Minimum dev-score delta to accept a challenger",
    )
    parser.add_argument(
        "--vital-threshold", type=float, default=1.0,
        help="Minimum vital-sign pass rate required for promotion",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--max-workers", type=int, default=1)
    parser.add_argument("--splits-path", default="benchmark/splits.json")
    parser.add_argument("--baselines-dir", default="results/baselines")
    parser.add_argument("--sensor-dir", default="results/sensor")
    parser.add_argument("--output-dir", default="results/differentiation")
    parser.add_argument("--bugsinpy-root", default=str(DEFAULT_BUGSINPY_ROOT))
    parser.add_argument(
        "--initial-config", default=None,
        help="Path to YAML config to start from (default: vanilla config)",
    )
    args = parser.parse_args()

    setup_logging()

    if not args.api_key and not args.dry_run:
        sys.exit("ERROR: set OPENAI_API_KEY or pass --api-key (or use --dry-run)")

    splits_path = Path(args.splits_path)
    if not splits_path.exists():
        sys.exit(f"ERROR: {splits_path} not found; run run_baselines.py first")

    splits = load_json(splits_path)
    dev_ids: list[str] = splits["dev"]
    vital_ids: list[str] = splits["vital_signs"]
    calib_ids: list[str] = splits["calibration"]

    logger.info(
        "Splits loaded: dev=%d  vital_signs=%d  calibration=%d  test=%d",
        len(dev_ids), len(vital_ids), len(calib_ids), len(splits.get("test", [])),
    )

    vanilla_path = Path(args.baselines_dir) / "vanilla_direct.json"
    solved_calib_ids: list[str] = []
    if vanilla_path.exists():
        vd = load_json(vanilla_path)
        solved_calib_ids = [
            tid for tid in calib_ids
            if vd.get("results", {}).get(tid, {}).get("passed", False)
        ]
        logger.info("Solved calibration tasks (for add_exemplar): %d", len(solved_calib_ids))

    sensor_report: SensorReport | None = None
    sensor_path = Path(args.sensor_dir) / "sensor_report.json"
    if sensor_path.exists():
        sensor_report = SensorReport.load(sensor_path)
        logger.info("Sensor report loaded. Suggested mutations: %s", sensor_report.suggested_mutations)
    else:
        logger.warning(
            "%s not found; running without sensor guidance (equivalent to no_sensor ablation)",
            sensor_path,
        )

    bugsinpy_root = Path(args.bugsinpy_root)
    all_needed_ids = list(dict.fromkeys(dev_ids + vital_ids + calib_ids))
    task_map = {}
    if args.dry_run:
        logger.info("Dry run: skipping BugsInPy checkouts")
    else:
        for idx, tid in enumerate(all_needed_ids, start=1):
            project, bug_id = tid.split(":", 1)
            started = time.perf_counter()
            logger.info("Loading task %d/%d: %s", idx, len(all_needed_ids), tid)
            try:
                task = load_bugsinpy_task(
                    project, bug_id, bugsinpy_root,
                    DEFAULT_WORKSPACE_ROOT, DEFAULT_CACHE_ROOT,
                )
                task_map[tid] = task
                logger.info(
                    "Loaded task %d/%d: %s (%.1fs)",
                    idx,
                    len(all_needed_ids),
                    tid,
                    time.perf_counter() - started,
                )
            except Exception as exc:
                logger.warning(
                    "Failed to load task %d/%d: %s after %.1fs: %s",
                    idx,
                    len(all_needed_ids),
                    tid,
                    time.perf_counter() - started,
                    exc,
                )

    logger.info("Loaded %d/%d BugsInPy tasks", len(task_map), len(all_needed_ids))

    solved_calib_tasks = [task_map[tid] for tid in solved_calib_ids if tid in task_map]

    if args.initial_config:
        initial = AgentConfig.from_yaml(Path(args.initial_config))
        logger.info("Starting from config: %s", args.initial_config)
    else:
        initial = AgentConfig()
        logger.info("Starting from default vanilla config")

    output_dir = Path(args.output_dir)
    if args.dry_run and args.output_dir == "results/differentiation":
        output_dir = Path("results/differentiation_dry_run")

    llm = LLMClient(
        api_key=args.api_key or "dry-run-key",
        default_model=args.model,
        log_dir=output_dir,
    )
    rng = random.Random(args.seed)
    mutator = Mutator(rng=rng)
    safeguard = Safeguard(vital_tasks=vital_ids, threshold=args.vital_threshold)

    output_dir.mkdir(parents=True, exist_ok=True)
    initial.save(output_dir / "initial_config.yaml")

    differentiator = Differentiator(
        llm_client=llm,
        mutator=mutator,
        safeguard=safeguard,
        tasks=task_map,
        dev_task_ids=dev_ids,
        vital_task_ids=vital_ids,
        log_dir=output_dir,
        sensor_report=sensor_report,
        solved_calibration_tasks=solved_calib_tasks,
        max_iterations=args.max_iterations,
        min_improvement=args.min_improvement,
        rng=rng,
        dry_run=args.dry_run,
        max_workers=args.max_workers,
    )

    logger.info(
        "Starting differentiation: max_iterations=%d  vital_threshold=%.2f  dry_run=%s  max_workers=%d",
        args.max_iterations, args.vital_threshold, args.dry_run, args.max_workers,
    )
    result = differentiator.run(initial)

    accepted = sum(1 for r in result.history if r.accepted)
    safeguard_rejections = sum(1 for r in result.history if r.reason == "safeguard")
    no_improvement = sum(1 for r in result.history if r.reason == "no_improvement")

    summary = {
        "final_score": result.final_score,
        "total_iterations": result.total_iterations,
        "converged": result.converged,
        "accepted_mutations": accepted,
        "safeguard_rejections": safeguard_rejections,
        "no_improvement_rejections": no_improvement,
        "total_cost_usd": result.total_cost_usd,
        "model": args.model,
        "max_iterations": args.max_iterations,
        "vital_threshold": args.vital_threshold,
        "dry_run": args.dry_run,
        "benchmark": "bugsinpy",
    }
    save_json(output_dir / "differentiation_summary.json", summary)

    logger.info("\n=== Differentiation Summary ===")
    logger.info("  Final dev score   : %.3f", result.final_score)
    logger.info("  Total iterations  : %d", result.total_iterations)
    logger.info("  Converged         : %s", result.converged)
    logger.info("  Accepted          : %d", accepted)
    logger.info("  Safeguard rejects : %d", safeguard_rejections)
    logger.info("  No-improvement    : %d", no_improvement)
    logger.info("  Total API cost    : $%.4f", result.total_cost_usd)
    logger.info("  Final config      : %s", output_dir / "final_champion.yaml")


if __name__ == "__main__":
    main()
