#!/usr/bin/env python3
"""
Run the Sensor on calibration results to extract failure signals.

Prerequisites
-------------
- benchmark/splits.json must exist (generated by run_baselines.py)
- results/baselines/vanilla_direct.json must exist

Outputs
-------
results/sensor/sensor_report.json
"""
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import DEFAULT_MODEL
from src.evaluator import load_tasks_from_dir
from src.llm_client import LLMClient
from src.sensor import Sensor
from src.utils import load_env_file, load_json, setup_logging

logger = logging.getLogger(__name__)


def main() -> None:
    load_env_file()

    parser = argparse.ArgumentParser(description="Run Sensor analysis on the calibration split")
    parser.add_argument("--api-key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default=DEFAULT_MODEL, help="LLM for sensor analysis")
    parser.add_argument("--splits-path", default="benchmark/splits.json")
    parser.add_argument("--baselines-dir", default="results/baselines")
    parser.add_argument("--output", default="results/sensor/sensor_report.json")
    parser.add_argument("--benchmark-dir", default="benchmark/tasks")
    args = parser.parse_args()

    setup_logging()

    if not args.api_key:
        sys.exit("ERROR: set OPENAI_API_KEY or pass --api-key")

    splits_path = Path(args.splits_path)
    if not splits_path.exists():
        sys.exit(f"ERROR: {splits_path} not found; run run_baselines.py first")

    vanilla_path = Path(args.baselines_dir) / "vanilla_direct.json"
    if not vanilla_path.exists():
        sys.exit(f"ERROR: {vanilla_path} not found; run run_baselines.py first")

    splits = load_json(splits_path)
    vanilla_data = load_json(vanilla_path)

    calib_ids = set(splits["calibration"])
    vanilla_results_raw = vanilla_data["results"]

    calib_passed: dict[str, bool] = {
        tid: info["passed"]
        for tid, info in vanilla_results_raw.items()
        if tid in calib_ids
    }
    calib_fixes: dict[str, str] = {
        tid: info.get("fix", "")
        for tid, info in vanilla_results_raw.items()
        if tid in calib_ids
    }

    all_tasks = load_tasks_from_dir(args.benchmark_dir)
    task_map = {task.task_id: task for task in all_tasks}
    calib_tasks = [task_map[tid] for tid in splits["calibration"] if tid in task_map]

    logger.info(
        "Sensor: %d calibration tasks loaded. pass@1 on calibration: %.3f",
        len(calib_tasks),
        sum(calib_passed.values()) / len(calib_passed) if calib_passed else 0.0,
    )

    llm = LLMClient(api_key=args.api_key, default_model=args.model)
    sensor = Sensor(llm_client=llm)

    report = sensor.analyze(
        calibration_tasks=calib_tasks,
        results=calib_passed,
        agent_fixes=calib_fixes,
    )

    output_path = Path(args.output)
    report.save(output_path)

    logger.info("\n=== Sensor Report ===")
    logger.info(
        "Analysis scope     : %s (reference fixes used: %s)",
        report.analysis_scope,
        report.reference_fixes_used,
    )
    logger.info("Category counts     : %s", report.category_counts)
    logger.info(
        "Category performance: %s",
        {key: f"{value:.2f}" for key, value in report.category_performance.items()},
    )
    logger.info("Failure patterns    : %s", report.failure_patterns)
    logger.info("Success patterns    : %s", report.success_patterns)
    logger.info("Suggested mutations : %s", report.suggested_mutations)
    logger.info("Saved to %s", output_path)
    logger.info("Total API cost: $%.4f", llm.get_total_cost())


if __name__ == "__main__":
    main()
